service: SongGame1

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1  # Set your desired AWS region

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
