service: SongGame1

provider:
  name: aws
  runtime: nodejs20.x  # Updated runtime
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
